# pyright: reportUnusedCallResult=false

from __future__ import annotations

import argparse


def get_args():
    parser = argparse.ArgumentParser("DINO R50 4-scale for NYCU VRDL HW2")

    parser.add_argument("--output_dir", default="outputs/dino_r50_4scale")
    parser.add_argument("--data_path", default="data/nycu-hw2-data")
    parser.add_argument("--batch_size", default=4, type=int)
    parser.add_argument("--num_workers", default=4, type=int)
    parser.add_argument("--epochs", default=24, type=int)
    parser.add_argument("--lr_drop", default=20, type=int)
    parser.add_argument("--lr", default=1e-4, type=float)
    parser.add_argument("--lr_backbone", default=1e-5, type=float)
    parser.add_argument("--weight_decay", default=1e-4, type=float)
    parser.add_argument("--clip_max_norm", default=0.1, type=float)
    parser.add_argument("--num_queries", default=900, type=int)
    parser.add_argument("--num_feature_levels", default=4, type=int)
    parser.add_argument("--hidden_dim", default=256, type=int)
    parser.add_argument("--dn_number", default=100, type=int)
    parser.add_argument("--dn_label_noise_ratio", default=0.5, type=float)
    parser.add_argument("--dn_box_noise_scale", default=0.4, type=float)
    parser.add_argument("--num_classes", default=11, type=int)
    parser.add_argument("--resume", default="")
    parser.add_argument("--start_epoch", default=0, type=int)
    parser.add_argument("--eval", action="store_true")
    parser.add_argument("--test", action="store_true")
    parser.add_argument("--checkpoint", default="")
    parser.add_argument("--amp", dest="amp", action="store_true")
    parser.add_argument("--no_amp", dest="amp", action="store_false")
    parser.set_defaults(amp=True)
    parser.add_argument("--amp_dtype", default="bf16", choices=["fp16", "bf16"])
    parser.add_argument("--debug_max_iters", default=None, type=int)
    parser.add_argument("--seed", default=42, type=int)
    parser.add_argument("--device", default="cuda")

    parser.add_argument("--backbone", default="resnet50")
    parser.add_argument("--position_embedding", default="sine")
    parser.add_argument("--dilation", action="store_true")
    parser.add_argument("--return_interm_indices", default=[1, 2, 3], nargs="+", type=int)
    parser.add_argument("--nheads", default=8, type=int)
    parser.add_argument("--enc_layers", default=6, type=int)
    parser.add_argument("--dec_layers", default=6, type=int)
    parser.add_argument("--dim_feedforward", default=2048, type=int)
    parser.add_argument("--dropout", default=0.0, type=float)
    parser.add_argument("--transformer_activation", default="relu")
    parser.add_argument("--dec_n_points", default=4, type=int)
    parser.add_argument("--enc_n_points", default=4, type=int)
    parser.add_argument("--two_stage", dest="two_stage", action="store_true")
    parser.add_argument("--no_two_stage", dest="two_stage", action="store_false")
    parser.set_defaults(two_stage=True)
    parser.add_argument("--mixed_selection", dest="mixed_selection", action="store_true")
    parser.add_argument("--no_mixed_selection", dest="mixed_selection", action="store_false")
    parser.set_defaults(mixed_selection=True)
    parser.add_argument("--look_forward_twice", dest="look_forward_twice", action="store_true")
    parser.add_argument("--no_look_forward_twice", dest="look_forward_twice", action="store_false")
    parser.set_defaults(look_forward_twice=True)
    parser.add_argument("--aux_loss", dest="aux_loss", action="store_true")
    parser.add_argument("--no_aux_loss", dest="aux_loss", action="store_false")
    parser.set_defaults(aux_loss=True)
    parser.add_argument("--with_box_refine", dest="with_box_refine", action="store_true")
    parser.add_argument("--no_with_box_refine", dest="with_box_refine", action="store_false")
    parser.set_defaults(with_box_refine=True)

    parser.add_argument("--focal_alpha", default=0.25, type=float)
    parser.add_argument("--focal_gamma", default=2.0, type=float)
    parser.add_argument("--cls_loss_coef", default=1.0, type=float)
    parser.add_argument("--bbox_loss_coef", default=5.0, type=float)
    parser.add_argument("--giou_loss_coef", default=2.0, type=float)
    parser.add_argument("--set_cost_class", default=2.0, type=float)
    parser.add_argument("--set_cost_bbox", default=5.0, type=float)
    parser.add_argument("--set_cost_giou", default=2.0, type=float)

    parser.add_argument("--data_aug_scales", default=[320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640], nargs="+", type=int)
    parser.add_argument("--data_aug_max_size", default=1024, type=int)
    parser.add_argument("--coco_path", default="data/nycu-hw2-data")

    parser.add_argument("--dist_url", default="env://")
    parser.add_argument("--world_size", default=1, type=int)
    parser.add_argument("--rank", default=0, type=int)
    parser.add_argument("--gpu", default=0, type=int)
    parser.add_argument("--distributed", action="store_true")

    parser.add_argument("--wandb", dest="wandb", action="store_true")
    parser.add_argument("--no_wandb", dest="wandb", action="store_false")
    parser.set_defaults(wandb=True)
    parser.add_argument("--wandb_project", default="vrdl-hw2")
    parser.add_argument("--wandb_name", default=None)
    parser.add_argument("--wandb_mode", default="online", choices=["online", "offline", "disabled"])
    parser.add_argument("--wandb_log_freq", default=10, type=int)

    return parser
